name: Bug Report
description: Report a bug in TagLibSharp2
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Create a BinaryData with...
        2. Call method...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: TagLibSharp2 Version
      description: What version of TagLibSharp2 are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    id: framework
    attributes:
      label: Target Framework
      description: Which .NET framework are you targeting?
      options:
        - .NET 10.0
        - .NET 8.0
        - .NET Standard 2.1
        - .NET Standard 2.0
        - Other (please specify in description)
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, stack traces, or screenshots.
