name: Feature Request
description: Suggest a new feature for TagLibSharp2
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe what you'd like to see.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: I would like TagLibSharp2 to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.

  - type: dropdown
    id: format
    attributes:
      label: Related Audio Format
      description: If this relates to a specific audio format, which one?
      options:
        - Not format-specific
        - MP3 (ID3v1/ID3v2)
        - FLAC
        - Vorbis/OGG
        - MP4/M4A
        - Other (please specify)

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples.
